const imageUrls = [
  // --- Species Images (12) ---
  "https://sbutltmedia.github.io/CDN/Isopod/species-armadillidium-nasatum.jpg",
  "https://sbutltmedia.github.io/CDN/Isopod/species-armadillidium-vulgare.jpg",
  "https://sbutltmedia.github.io/CDN/Isopod/species-ligidium-longicaudatum.jpg",
  "https://sbutltmedia.github.io/CDN/Isopod/species-trichoniscus-pusillus.jpg",
  "https://sbutltmedia.github.io/CDN/Isopod/species-haplophthalmus-danicus.jpg",
  "https://sbutltmedia.github.io/CDN/Isopod/species-oniscus-asellus.jpg",
  "https://sbutltmedia.github.io/CDN/Isopod/species-metoponorthus-pruinosus.jpg",
  "https://sbutltmedia.github.io/CDN/Isopod/species-cylisticus-convexus.jpg",
  "https://sbutltmedia.github.io/CDN/Isopod/species-porcellio-laevis.jpg",
  "https://sbutltmedia.github.io/CDN/Isopod/species-porcellio-spinicornis.jpg",
  "https://sbutltmedia.github.io/CDN/Isopod/species-porcellio-scaber.jpg",
  "https://sbutltmedia.github.io/CDN/Isopod/species-porcellio-rathkei.jpg",

  // --- Feature Images (22) ---
  "https://sbutltmedia.github.io/CDN/Isopod/feature-short-uropods.jpg",
  "https://sbutltmedia.github.io/CDN/Isopod/feature-long-uropods.jpg",
  "https://sbutltmedia.github.io/CDN/Isopod/feature-notched-frontal-line.jpg",
  "https://sbutltmedia.github.io/CDN/Isopod/feature-smooth-frontal-line.jpg",
  "https://sbutltmedia.github.io/CDN/Isopod/feature-rounded-abdominal-segment.jpg",
  "https://sbutltmedia.github.io/CDN/Isopod/feature-triangular-abdominal-segment.jpg",
  "https://sbutltmedia.github.io/CDN/Isopod/feature-11-antenna-segments.jpg",
  "https://sbutltmedia.github.io/CDN/Isopod/feature-3-to-4-antenna-segments.jpg",
  "https://sbutltmedia.github.io/CDN/Isopod/feature-3-eye-facets.jpg",
  "https://sbutltmedia.github.io/CDN/Isopod/feature-1-eye-facet.jpg",
  "https://sbutltmedia.github.io/CDN/Isopod/feature-3-antenna-segments.jpg",
  "https://sbutltmedia.github.io/CDN/Isopod/feature-2-antenna-segments.jpg",
  "https://sbutltmedia.github.io/CDN/Isopod/feature-abdomen-narrower.jpg",
  "https://sbutltmedia.github.io/CDN/Isopod/feature-abdomen-not-narrower.jpg",
  "https://sbutltmedia.github.io/CDN/Isopod/feature-smooth-dorsal-surface.jpg",
  "https://sbutltmedia.github.io/CDN/Isopod/feature-bumpy-dorsal-surface.jpg",
  "https://sbutltmedia.github.io/CDN/Isopod/feature-extremely-convex-body.jpg",
  "https://sbutltmedia.github.io/CDN/Isopod/feature-moderately-convex-body.jpg",
  "https://sbutltmedia.github.io/CDN/Isopod/feature-head-contrasts-thorax.jpg",
  "https://sbutltmedia.github.io/CDN/Isopod/feature-head-not-contrasting.jpg",
  "https://sbutltmedia.github.io/CDN/Isopod/feature-2-pairs-white-bodies.jpg",
  "https://sbutltmedia.github.io/CDN/Isopod/feature-5-pairs-white-bodies.jpg"
];